### ISSUE TITLE
Chartist Charts Not Working for Logged Out Users

### ISSUE THREAD

**Issue by cgrymala** [wpcampus/wpcampus-wp-theme#1]
Initial reports made it seem like the new Chartist charts weren't working in Firefox, but, after a bit of investigation, it looks like they're failing for anyone that's not logged into the site, regardless of browser. I've tested logged-out in Firefox, Chrome, Opera, IE and Edge on Windows 10. I've tested logged-in in Firefox & Chrome.

Not sure what's actually causing the error, but the browser consoles seem to indicate that, when logged out, the chartist var "a" is undefined.

Will need to investigate further.

![wpcampus-chartist-error](https://cloud.githubusercontent.com/assets/249000/9699439/f35801ea-53b0-11e5-88bb-bd614d49881f.png)

**Comment by cgrymala** [comment]
I believe I've found the issue. Strange that it seemed to be manifesting itself as a logged-in/logged-out problem, as that may just be a coincidence.

It looks like the root of the problem is that the chartist commands were firing too early in the page; they were trying to target HTML elements before the DOM had finished loading, so it was a bit of a crapshoot as to whether they'd find the elements or not.

I'm testing some changes to the JS that tell the Chartist commands to wait until the document is ready.

**Comment by bamadesigner** [comment]
Thanks @cgrymala!
